version: '3'

services:
  web:
    build:
	context: .
	dockerfile: Dockerfile 
    command: gunicorn nginxtestdjango.nginxtestdjango.wsgi --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8888:80"
    depends_on:
      - web

